package ru.demoexam.shoestore.db;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

public class SchemaInitializer {
    private final Database database;

    public SchemaInitializer(Database database) {
        this.database = database;
    }

    public void initialize() {
        try (Connection connection = database.getConnection();
             Statement statement = connection.createStatement()) {
            statement.execute("""
                CREATE TABLE IF NOT EXISTS users (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    full_name TEXT NOT NULL,
                    login TEXT NOT NULL UNIQUE,
                    password TEXT NOT NULL,
                    role TEXT NOT NULL
                )
                """);

            statement.execute("""
                CREATE TABLE IF NOT EXISTS categories (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name TEXT NOT NULL UNIQUE
                )
                """);

            statement.execute("""
                CREATE TABLE IF NOT EXISTS manufacturers (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name TEXT NOT NULL UNIQUE
                )
                """);

            statement.execute("""
                CREATE TABLE IF NOT EXISTS suppliers (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name TEXT NOT NULL UNIQUE
                )
                """);

            statement.execute("""
                CREATE TABLE IF NOT EXISTS pickup_points (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    address TEXT NOT NULL UNIQUE
                )
                """);

            statement.execute("""
                CREATE TABLE IF NOT EXISTS products (
                    article TEXT PRIMARY KEY,
                    name TEXT NOT NULL,
                    category_id INTEGER NOT NULL REFERENCES categories(id),
                    description TEXT NOT NULL,
                    manufacturer_id INTEGER NOT NULL REFERENCES manufacturers(id),
                    supplier_id INTEGER NOT NULL REFERENCES suppliers(id),
                    price NUMERIC(10, 2) NOT NULL CHECK(price >= 0),
                    unit TEXT NOT NULL,
                    stock_quantity INTEGER NOT NULL CHECK(stock_quantity >= 0),
                    discount_percent INTEGER NOT NULL CHECK(discount_percent >= 0),
                    image_path TEXT
                )
                """);

            statement.execute("""
                CREATE TABLE IF NOT EXISTS orders (
                    id INTEGER PRIMARY KEY,
                    pickup_point_id INTEGER NOT NULL REFERENCES pickup_points(id),
                    client_full_name TEXT NOT NULL,
                    pickup_code INTEGER NOT NULL,
                    status TEXT NOT NULL,
                    order_date DATE NOT NULL,
                    delivery_date DATE NOT NULL
                )
                """);

            statement.execute("""
                CREATE TABLE IF NOT EXISTS order_items (
                    order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
                    product_article TEXT NOT NULL REFERENCES products(article),
                    quantity INTEGER NOT NULL CHECK(quantity > 0),
                    PRIMARY KEY (order_id, product_article)
                )
                """);

            if (isEmpty(connection, "users")) {
                seedUsers(connection);
                seedLookups(connection);
                seedProducts(connection);
                seedOrders(connection);
            }
        } catch (Exception exception) {
            throw new IllegalStateException("Не удалось инициализировать базу данных.", exception);
        }
    }

    private boolean isEmpty(Connection connection, String tableName) throws Exception {
        try (PreparedStatement statement = connection.prepareStatement("SELECT COUNT(*) FROM " + tableName);
             ResultSet resultSet = statement.executeQuery()) {
            return resultSet.next() && resultSet.getInt(1) == 0;
        }
    }

    private void seedUsers(Connection connection) throws Exception {
        connection.createStatement().executeUpdate("""
            INSERT INTO users(full_name, login, password, role) VALUES
            ('Ворсин Петр Евгеньевич', '94d5ous@gmail.com', 'uzWC67', 'ADMIN'),
            ('Старикова Елена Павловна', 'uth4iz@mail.com', '2L6KZG', 'ADMIN'),
            ('Орлова Марина Викторовна', 'manager', 'manager', 'MANAGER'),
            ('Михайлюк Анна Вячеславовна', 'client', 'client', 'CLIENT')
            """);
    }

    private void seedLookups(Connection connection) throws Exception {
        connection.createStatement().executeUpdate("""
            INSERT INTO categories(name) VALUES
            ('Общестроительные материалы'),
            ('Лакокрасочные материалы'),
            ('Инструменты')
            """);

        connection.createStatement().executeUpdate("""
            INSERT INTO manufacturers(name) VALUES
            ('М500'),
            ('Изостронг'),
            ('Makita')
            """);

        connection.createStatement().executeUpdate("""
            INSERT INTO suppliers(name) VALUES
            ('М500'),
            ('Изостронг'),
            ('Makita')
            """);

        connection.createStatement().executeUpdate("""
            INSERT INTO pickup_points(address) VALUES
            ('420151, г. Лесной, ул. Вишневая, 32'),
            ('125061, г. Лесной, ул. Подгорная, 8'),
            ('630370, г. Лесной, ул. Шоссейная, 24')
            """);
    }

    private void seedProducts(Connection connection) throws Exception {
        connection.createStatement().executeUpdate("""
            INSERT INTO products(article, name, category_id, description, manufacturer_id, supplier_id, price, unit, stock_quantity, discount_percent, image_path) VALUES
            ('PMEZMH', 'Цемент', 1, 'Цемент Евроцемент М500 Д0 ЦЕМ I 42,5 50 кг', 1, 1, 440.00, 'шт.', 34, 8, NULL),
            ('BPV4MM', 'Пленка техническая', 1, 'Пленка техническая полиэтиленовая Изостронг 60 мк 3 м рукав 1,5 м, пог.м', 2, 2, 8.00, 'шт.', 2, 8, NULL),
            ('3XBOTN', 'Шуруповерт', 3, 'Аккумуляторный шуруповерт для монтажных работ', 3, 3, 8990.00, 'шт.', 7, 5, NULL)
            """);
    }

    private void seedOrders(Connection connection) throws Exception {
        connection.createStatement().executeUpdate("""
            INSERT INTO orders(id, pickup_point_id, client_full_name, pickup_code, status, order_date, delivery_date) VALUES
            (1, 1, 'Михайлюк Анна Вячеславовна', 901, 'Завершен', '2025-02-27', '2025-04-20'),
            (2, 2, 'Ситдикова Елена Анатольевна', 902, 'Завершен', '2024-09-28', '2025-04-21')
            """);

        connection.createStatement().executeUpdate("""
            INSERT INTO order_items(order_id, product_article, quantity) VALUES
            (1, 'PMEZMH', 2),
            (1, 'BPV4MM', 2),
            (2, 'PMEZMH', 1),
            (2, '3XBOTN', 1)
            """);
    }
}
